#pragma once
#ifndef _XSL_NET_TRANSPORT_DEF_H_
#  define _XSL_NET_TRANSPORT_DEF_H_

#  define TRANSPORT_NAMESPACE_BEGIN namespace xsl::net::transport::detail {
#  define TRANSPORT_NAMESPACE_END }
TRANSPORT_NAMESPACE_BEGIN
const int MAX_CONNECTIONS = 10;
TRANSPORT_NAMESPACE_END
#endif  // _XSL_NET_TRANSPORT_DEF_H_
