# ---- Add Subdirectories ----
add_subdirectory(coro)
add_subdirectory(dns)
add_subdirectory(feature)
add_subdirectory(regex)
add_subdirectory(wheel)
add_subdirectory(sys)
add_subdirectory(sync)
add_subdirectory(http)
add_subdirectory(ser)
add_subdirectory(net)
# ---- compose standalone test ----
add_executable(compose compose.cpp)
target_include_directories(compose PRIVATE ${PROJECT_SOURCE_DIR}/include)
target_link_libraries(compose PRIVATE GTest::gtest_main)
add_test(NAME compose COMMAND compose)
